# Import Numpy

In [1]:
import numpy as np

# Creating NumPy arrays
There are many ways to create arrays in NumPy. 

In [2]:
data = np.array([1, 2, 3, 4, 5])   # Create a rank 1 array

In [3]:
print(data)

[1 2 3 4 5]


In [4]:
ones=np.ones(5)
print(ones)

[1. 1. 1. 1. 1.]


In [5]:
zeros=np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [6]:
random=np.random.random(5)
print(random)

[0.57606136 0.92392408 0.73610303 0.15864494 0.22295509]


# Array Arithmetic Operations

In [7]:
addition = data + ones 
print(addition)

[2. 3. 4. 5. 6.]


In [8]:
multiplication= data*zeros
print (multiplication)

[0. 0. 0. 0. 0.]


# Indexing & Slicing

In [9]:
i1=data[0]
print(i1)

1


In [10]:
i=2
i2=data[i]
print(i2)

3


In [11]:
slice=data[2:3]  #this slice looks similar to indexed value. But slice is an array whereas index is about values
print(slice)

[3]


In [12]:
slice1=data[0:2]
print(slice1)

[1 2]


In [13]:
slice2=data[1:]
print(slice2)

[2 3 4 5]


In [14]:
slice2=data[:5]
print(slice2)

[1 2 3 4 5]


# Aggregation

In [15]:
print(data.max())
print(data.min())
print(data.sum())

5
1
15


# Exercise

Create an array of length 8. Create two slices - one with first 4 elements and another with last 4 elements. Add the two slices and print the result.

In [19]:
arr = 100*np.random.random(8)
print(arr)

[16.93810083 55.36552496 24.60542936 60.19223863 25.02789221 79.54470596
 40.06739575 65.81166497]


In [22]:
slice_sum = arr[:4] + arr[4:]
print('Result of two slices summing : {}'.format(slice_sum))

Result of two slices summing : [ 41.96599304 134.91023092  64.67282511 126.00390359]
