# Import Numpy

In [1]:
import numpy as np

# Creating Matrix: 2-D Array

In [2]:
# Create the following rank 2 array with shape (3, 2)

data = np.array([[1,2], [3,4], [5,6]])
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [3]:
ones=np.ones((3,2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [4]:
zeros=np.zeros((3,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [5]:
random=np.random.random((3,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


# Matrix Arithmetic Operations

In [6]:
addition = data + ones 
print(addition)

[[2. 3.]
 [4. 5.]
 [6. 7.]]


In [7]:
np.add(data, ones)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [8]:
multiplication= data*zeros
print (multiplication)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [9]:
np.multiply(data, zeros)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Matrix Indexing and Slicing

In [10]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
index1=data[0,1]
print(index1)

2


In [12]:
slice1=data[0:2]
print(slice1)

[[1 2]
 [3 4]]


In [13]:
slice2=data[0:2,0]
print(slice2)

[1 3]


# Matrix Aggregation

In [14]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


# Transposing

In [15]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
dataT=data.T
print(dataT)

[[1 3 5]
 [2 4 6]]


In [17]:
data.shape

(3, 2)

In [18]:
dataT.shape

(2, 3)

In [19]:
np.matmul(data, data.T)

array([[ 5, 11, 17],
       [11, 25, 39],
       [17, 39, 61]])

# Reshaping

In [20]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
data_vertical=data.reshape(6,1)
print(data_vertical)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [22]:
data_horizontal=data.reshape(1,6)
print(data_horizontal)

[[1 2 3 4 5 6]]


In [23]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
data_landscape=data.reshape(2,3)
print(data_landscape)

[[1 2 3]
 [4 5 6]]


# Big Matrix

In [25]:
la= np.arange(36) #creates array of numbers from 0 to 36

In [26]:
print(la)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]


In [27]:
la.shape

(36,)

In [28]:
bm=la.reshape(6,6)

In [29]:
print(bm)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


# Exercise

In [30]:
bm

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [31]:
bm[1:5, 1]

array([ 7, 13, 19, 25])

In [32]:
bm[1, 1:]

array([ 7,  8,  9, 10, 11])

In [33]:
bm[3:,3:]

array([[21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])